config/routes.rb
TunrApp::Application.routes.draw do
  resources :musicians  
  resources :bands
end

app/models/band.rb
class Band < ActiveRecord::Base

	attr_accessible :name 

	def self.invent_name 
		Faker::Name.first_name + " and the "+ Faker::Commerce.product_name
	end

end

app/models/musician.rb
class Musician < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	def new
		@band = Band.new
	end

	def create
		Band.create(name: params[:band][:name])
		redirect_to bands_path
	end
  
  def index
  	@bands = Band.all
  end

  def show 
  	@band = Band.find(params[:id])
  end

  def edit 
  	@band = Band.find(params[:id])
  end

  def update
  	band = Band.find(params[:id])
  	band.name = params[:band][:name]
  	band.save
    redirect_to band_path(band)
  end

  def destroy
  	Band.delete(params[:id])
    redirect_to bands_path
  end

end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
	def new
		@musician = Musician.new
	end

	def create
		name = params[:name] || params[:musician][:name]
		Musician.create(name: name)
		redirect_to musicians_path
	end

	def index
		@musicians = Musician.all 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/_band_form.html.erb
<%= form_for band  do |f| %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
	<%= f.submit nil, class:"btn btn-primary", id:"submit" %>
<% end %>

# <%= form_tag("/bands/search", method: "get") do%> 
# 	<%= label_tag(:band, "band") %>
# 	<%= text_field_tag(:band) %> 
# 	<%= submit_tag("Find Musician") %>
# <% end %>

app/views/bands/_contact_info.html.erb
<h1>ME: THE_BROW@generalassemb.ly</h1>

app/views/bands/edit.html.erb
<h1>DRUMMER DEAD. LEAD SINGER HEROINE. RENAME. </h1>

<%= render partial: "band_form", locals: {band: @band} %>

<%= render partial: "contact_info" %>

app/views/bands/index.html.erb
<table class="table table-hover table-bordered">
	<% @bands.each do |band|  %>
	<tr class="band_<%=band.id%>">
		<td><%= band.name %></td>
		<td><a href="<%=band_path(band)%>">SHOW</a></td>
	<!-- 	<td><a href="/bands/<%=band.id%>/edit">EDIT</a></td> -->
		<td><a href="<%= edit_band_path(band) %>">EDIT</a></td>
		<td>
			<form action="<%=band_path(band)%>" method="post">
			<input type="hidden" value="delete" name="_method">
			<button class="delete btn-link">DELETE</button>
		</form>
		</td>
	</tr>
	<% end %>
</table>

app/views/bands/new.html.erb
<!-- A STRAIGHT UP HTML FORM -->

<!-- <form action="/bands" method="post">
	<input class="form-control" type="text"	name="name">
	<button class="btn btn-primary" id="submit">Create Band</button>
</form> -->

<!-- Rails Form Helper that takes a band object! -->
<h1>I KNOW THAT GARAGEBAND IS A DEMOCRATIZING FORCE IN OUR SOCIETY, BUT YOU SUCK.</h1>
<!-- 
<%= form_for @band  do |f| %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
	<%= f.submit nil, class:"btn btn-primary" %>
<% end %>
 -->

 <%= render partial: "band_form", locals: {band: @band} %>

app/views/bands/show.html.erb
<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-3">
		<h1 class="band_name">
			<%= @band.name %></h1>

		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis, harum maxime dolorem perspiciatis iure quos et esse consectetur obcaecati a architecto quibusdam corporis eos molestiae aspernatur. Eaque corporis vero aperiam!
		</p>
	</div>
	<div class="col-lg-9 col-md-3 col-sm-3">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam, rem, est, provident, doloremque sapiente id vitae voluptate tempora corporis dolorem consectetur incidunt molestiae praesentium aspernatur quas assumenda nobis. Eaque, nostrum quisquam suscipit alias enim veniam ipsam consequatur quas odio quia? Earum, sequi distinctio laboriosam ut explicabo quam iste vero facere!
		</p>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunrApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/musicians/index.html.erb
<table>
	<% @musicians.each do |musician|  %>
	<tr>
		<td><%= musician.name %></td>
		<td>SHOW</td>
		<td>EDIT</td>
		<td>DELETE</td>
	</tr>
	<% end %>
</table>